/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package components;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import models.BarangModel;

/**
 *
 * @author rizkyalam
 */
public class EditBarang extends javax.swing.JFrame {
    private int userId;
    private String userName;
    private BarangModel barangModel = new BarangModel();
    
    /**
     * Creates new form EditBarang
     */
    public EditBarang(int userId, String userName) throws SQLException {
        this.userId = userId;
        this.userName = userName;
        
        initComponents();
        setDaftarId(userId);
        setDataBarang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        editNameInput = new javax.swing.JTextField();
        daftarId = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        stockInput = new javax.swing.JTextField();
        editBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Edit Barang");

        jLabel2.setText("ID Barang");

        jLabel3.setText("Nama Barang");

        daftarId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                daftarIdItemStateChanged(evt);
            }
        });
        daftarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarIdActionPerformed(evt);
            }
        });

        jLabel4.setText("Stok");

        stockInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockInputActionPerformed(evt);
            }
        });

        editBtn.setText("ubah");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        backBtn.setText("kembali");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(editNameInput)
                            .addComponent(daftarId, 0, 170, Short.MAX_VALUE)
                            .addComponent(stockInput)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(editBtn)
                        .addGap(63, 63, 63)
                        .addComponent(backBtn)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(daftarId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(editNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(stockInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editBtn)
                    .addComponent(backBtn))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setDaftarId(int userId) throws SQLException {
        BarangModel barang = new BarangModel();
        ArrayList listId = barang.getAllId(userId);
        
        daftarId.setModel(new DefaultComboBoxModel(listId.toArray()));
    }
    
    private void stockInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockInputActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        try {
            int id = (int) daftarId.getSelectedItem();
            String name = editNameInput.getText();
            int stock = Integer.parseInt(stockInput.getText());
            
            barangModel.update(id, this.userId, name, stock);
            
            Barang barangForm = new Barang(this.userId, this.userName);
            barangForm.setVisible(true);
                    
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(TambahBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        try {
            Barang barangForm;
            barangForm = new Barang(this.userId, this.userName);
            barangForm.setVisible(true);
            
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(TambahBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_backBtnActionPerformed

    private void daftarIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_daftarIdItemStateChanged
        try {
            setDataBarang();
        } catch (SQLException ex) {
            Logger.getLogger(EditBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_daftarIdItemStateChanged

    private void setDataBarang() throws SQLException {
        int id = (int) daftarId.getSelectedItem();

        ArrayList<Object> barangData = barangModel.getById(id, this.userId);

        editNameInput.setText((String) barangData.get(0));
        stockInput.setText(Integer.toString((int) barangData.get(1)));
    }
    
    private void daftarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daftarIdActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox<String> daftarId;
    private javax.swing.JButton editBtn;
    private javax.swing.JTextField editNameInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nameInput;
    private javax.swing.JTextField nameInput1;
    private javax.swing.JTextField nameInput2;
    private javax.swing.JTextField nameInput3;
    private javax.swing.JTextField nameInput4;
    private javax.swing.JTextField stockInput;
    // End of variables declaration//GEN-END:variables
}
